### ISSUE TITLE
cocoapods-check 1.0.2 not working with cocoapods 1.5.3

### ISSUE THREAD

**Issue by kerryknight** [square/cocoapods-check#12]
Hi there, super excited to try this plug-in but I'm having a slight issue, that seems related to closed issue #6.  I'm receiving `"Unknown command: 'check'"` after install with cocoapods v1.5.3 installed.

Any suggestions?  Many thanks for any and all help!

![serialbox-ios_ _-bash_ _ttys001_ _156x46_and_serialbox-ios_-_build__129__8b2baf220c553e9c__-_bitrise](https://user-images.githubusercontent.com/4324674/50862406-8d063980-1369-11e9-9f4d-e7f633f943bc.png)

**Comment by mdiiorio** [comment]
Have you tried using Bundler? I don't have any experience using Cocoapods with directly installed gems, I've only used it through Bundler. I just tested with the following Gemfile and things seemed to work ok:

```
gem 'cocoapods', '~> 1.5.3'
gem 'cocoapods-check', '~> 1.0'
```

With Bundler you'd need to do something like (in the same directory as the Gemfile):

```
% bundle install
...
Using cocoapods 1.5.3
Using cocoapods-check 1.0.2
Bundle complete! 2 Gemfile dependencies, 31 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
% bundle exec pod check
The Podfile's dependencies are satisfied
```

**Comment by kerryknight** [comment]
Ah, yes switching to using bundler did it!  Thanks so much for the quick reply!  Closing.

**Comment by mdiiorio** [comment]
Great!
