### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by orta** [square/cocoapods-check#4]
Hey there, love the plugin, I'd like to integrate it into the CocoaPods Mac app as a part of https://github.com/CocoaPods/CocoaPods-app/issues/260 - any chance I can get a rubygems of the 0.2.1 release? 

Or if you're happy in production with it - a 1.0? 🌴

**Comment by mdiiorio** [comment]
Awesome! Would it be ok for it to be a beta release, since it's targeting CocoaPods 1.0 beta?

**Comment by orta** [comment]
Yep, totally, I'm locking to [specific versions](https://github.com/CocoaPods/CocoaPods-app/blob/dan-sources-management/Rakefile#L593).

**Comment by mdiiorio** [comment]
Ok, I just published 0.2.1.beta.1, which includes your recent PR.

**Comment by orta** [comment]
👍
