### ISSUE TITLE
cocoapods-check not working with cocoapods version 1.0.0

### ISSUE THREAD

**Issue by aashishtamsya** [square/cocoapods-check#6]
After executing pod check I got this error

![screen shot 2016-05-19 at 10 28 20 am](https://cloud.githubusercontent.com/assets/10719017/15383641/46808de4-1db2-11e6-8a07-7b550837a76d.png)

**Comment by mdiiorio** [comment]
Probably because the current tip of cocoapods-check is in beta. Let me do a 1.0.0 release and that should fix things. I've been meaning to do that anyway.

**Comment by mdiiorio** [comment]
Ok, 1.0.0 has been published. Can you update your Gemfile and give that a try?

**Comment by aashishtamsya** [comment]
Its working 😃😃😃👍👍👍

On Thursday 19 May 2016, Matt Diiorio notifications@github.com wrote:

> Ok, 1.0.0 has been published. Can you update your Gemfile and give that a
> try?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/square/cocoapods-check/issues/6#issuecomment-220332810

## 

Kind Regards,
Aashish Tamsya
