### ISSUE TITLE
Podfile.lock and Pods/Manifest.lock comparison not working

### ISSUE THREAD

**Issue by tristandl** [square/cocoapods-check#7]
I ran into a problem running pod check in our CircleCI build environment. I had updated a pod in my local build, and then the /Pods directory on the build server was out of date (had the wrong version of the pod in the Manifest.lock). 

If I did a diff on the two files, I had a different version number on the pod and a different checksum. If I ran pod check (v1.0.0 and cocoapods v1.0.1) it said Pods are up to date. My current work around is to do the diff myself, and run pod install if the files differ - it looks to me like this should be handled in /lib/pod/command/check.rb but it doesn't seem to be working. 

This issue might be related to #1 but it also relates to actual version mismatches, not just the checksum.

**Comment by mdiiorio** [comment]
Hey sorry I'm just now seeing this. Could you reply with the diff output?

**Comment by tristandl** [comment]
from memory it was the checksum and the pod version that were different - everything else was teh same. i don't know which build this was, it was a few weeks ago, and we have tons of failed builds.

**Comment by orta** [comment]
I have a PR for this #9

**Comment by mdiiorio** [comment]
Fixed in v1.0.2.
